In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('/content/Medical_Update_2.csv')
df

Unnamed: 0  Gender  Age  Systolic BP  Diastolic BP  Cholesterol  \
0              0       1   45          120            95          141   
1              1       0   45          147            85          197   
2              2       1   71          124            94          239   
3              3       1   39          112            95          227   
4              4       1   44          142            95          193   
...          ...     ...  ...          ...           ...          ...   
9995        9995       0   63          141            66          207   
9996        9996       1   18          138            81          199   
9997        9997       1   61          141            93          140   
9998        9998       1   18          115            93          239   
9999        9999       0   34          105            95          156   

            BMI  Smoker  Diabetes  Health  
0     22.630809       1         0       1  
1     27.349662       1         0       3  
2     23.115311       1         0       3  
3     31.492492       1         1       3  
4     22.783389       0         0       1  
...         ...     ...       ...     ...  
9995  20.277316       1         1       3  
9996  31.400026       0         0       1  
9997  21.679786       1         1       3  
9998  23.892676       1         1       3  
9999  18.883997       0         0       1  

[10000 rows x 10 columns]

In [4]:
X = df.iloc[:,1:9].values
y =df.iloc[:, -1].values

In [5]:
X

array([[  1.        ,  45.        , 120.        , ...,  22.63080911,
          1.        ,   0.        ],
       [  0.        ,  45.        , 147.        , ...,  27.34966234,
          1.        ,   0.        ],
       [  1.        ,  71.        , 124.        , ...,  23.11531134,
          1.        ,   0.        ],
       ...,
       [  1.        ,  61.        , 141.        , ...,  21.67978623,
          1.        ,   1.        ],
       [  1.        ,  18.        , 115.        , ...,  23.89267624,
          1.        ,   1.        ],
       [  0.        ,  34.        , 105.        , ...,  18.88399684,
          0.        ,   0.        ]])

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [9]:
print(sc.transform([[0,45,147,85,197,27.349662,1,0]]))

[[-0.86299809  0.34819373  1.03741399 -0.33855315  0.55417846  0.52571163
   1.11613132 -1.03756212]]


In [10]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3 3]
 [1 1]
 [2 2]
 ...
 [1 1]
 [2 2]
 [3 3]]


In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1086    9    0]
 [   1 1196    4]
 [   0    6  698]]


0.9933333333333333

In [12]:
print(classifier.predict(sc.transform([[1,44,142,95,193,22.783389,0,0]])))

[2]
